server {
    listen 80;

    location /api/students {
        proxy_pass http://student-service:8080/api/students;
        proxy_set_header Host $host;
    }

    location /api/courses {
        proxy_pass http://course-service:8080/api/courses;
        proxy_set_header Host $host;
    }

    location /api/enrollments {
        proxy_pass http://enrollment-service:8080/api/enrollments;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
